"""Purchase orders: ordered → received flow on top of the movement ledger.

A PurchaseOrder records what was ordered from a Supplier at which unit cost;
receiving goods against its lines generates the inbound Movements (the ledger
itself is unchanged — see services/purchasing.py). `quantity_received` on each
line is denormalized and only updated by PurchasingService under row lock.
"""
import uuid
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.db import models

from core.models import Company, User
from .core import ProductModel
from .suppliers import Supplier

PO_STATUS_DRAFT = 'DRAFT'
PO_STATUS_CONFIRMED = 'CONFIRMED'
PO_STATUS_PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED'
PO_STATUS_RECEIVED = 'RECEIVED'
PO_STATUS_CANCELLED = 'CANCELLED'

PO_STATUS_CHOICES = [
    (PO_STATUS_DRAFT, 'Draft'),
    (PO_STATUS_CONFIRMED, 'Confirmed'),
    (PO_STATUS_PARTIALLY_RECEIVED, 'Partially received'),
    (PO_STATUS_RECEIVED, 'Received'),
    (PO_STATUS_CANCELLED, 'Cancelled'),
]


class PurchaseOrder(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='purchase_orders')
    # PROTECT: an order is a commercial document — the supplier on it must
    # survive as long as the order does.
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, related_name='purchase_orders')
    # Sequential per company: PO-{year}-{progressive}. Generated by
    # PurchasingService under a company-row lock (no race on the progressive).
    number = models.CharField(max_length=32)
    status = models.CharField(max_length=30, choices=PO_STATUS_CHOICES, default=PO_STATUS_DRAFT)
    expected_at = models.DateField(null=True, blank=True)
    notes = models.TextField(blank=True)

    created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='purchase_orders')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('company', 'number')
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['company', 'status']),
        ]

    def clean(self):
        super().clean()
        if self.supplier_id and self.supplier.company_id != self.company_id:
            raise ValidationError({'supplier': "supplier belongs to a different company."})

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.number} ({self.supplier}) [{self.status}]"


class PurchaseOrderLine(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    purchase_order = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE, related_name='lines')
    product_model = models.ForeignKey(ProductModel, on_delete=models.PROTECT, related_name='purchase_order_lines')

    quantity_ordered = models.DecimalField(max_digits=12, decimal_places=4)
    unit_cost = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    # Denormalized; only PurchasingService.receive updates it, under
    # select_for_update on this row.
    quantity_received = models.DecimalField(max_digits=12, decimal_places=4, default=Decimal('0'))

    class Meta:
        unique_together = ('purchase_order', 'product_model')
        ordering = ['id']

    @property
    def quantity_pending(self) -> Decimal:
        return self.quantity_ordered - self.quantity_received

    def clean(self):
        super().clean()
        if self.quantity_ordered is None or self.quantity_ordered <= 0:
            raise ValidationError({'quantity_ordered': "Ordered quantity must be positive."})
        if self.unit_cost is not None and self.unit_cost < 0:
            raise ValidationError({'unit_cost': "Unit cost cannot be negative."})
        if self.product_model_id and self.purchase_order_id \
                and self.product_model.company_id != self.purchase_order.company_id:
            raise ValidationError({'product_model': "product_model belongs to a different company."})

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.purchase_order.number}: {self.quantity_ordered}× {self.product_model.sku}"
