"""Returns / RMA: customer and supplier return flow on top of the ledger.

A ReturnOrder records goods coming back. For a CUSTOMER_RETURN the goods are
received into the company's quarantine location (real, WAREHOUSE-type,
``is_sellable=False``) and then resolved per line — RESTOCK back to the
warehouse, SCRAP to LOSS, or RETURN_TO_SUPPLIER to the External vendor. A
SUPPLIER_RETURN ships goods already on hand back out to the vendor.

Every physical stock change goes through ``LedgerService.transfer_stock``
(see services/rma.py); these models only hold the document state.
``ReturnOrderLine.resolution`` is the per-line decision and is only mutated by
RmaService under row lock.
"""
import uuid

from django.core.exceptions import ValidationError
from django.db import models

from core.models import Company, User
from .. import constants
from .core import ProductModel, Location
from .customers import Customer
from .suppliers import Supplier
from .tracking import PhysicalProduct, ProductBatch
from .purchasing import PurchaseOrder
from .sales import SalesOrder


class ReturnOrder(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='return_orders')
    kind = models.CharField(max_length=30, choices=constants.RMA_KINDS)
    # Exactly one of customer / supplier is set (clean()), matching `kind`.
    customer = models.ForeignKey(
        Customer, null=True, blank=True, on_delete=models.PROTECT, related_name='return_orders',
    )
    supplier = models.ForeignKey(
        Supplier, null=True, blank=True, on_delete=models.PROTECT, related_name='return_orders',
    )
    # Optional link to the order the goods originally came from.
    sales_order = models.ForeignKey(
        SalesOrder, null=True, blank=True, on_delete=models.SET_NULL, related_name='return_orders',
    )
    purchase_order = models.ForeignKey(
        PurchaseOrder, null=True, blank=True, on_delete=models.SET_NULL, related_name='return_orders',
    )
    # Sequential per company: RMA-{year}-{progressive}. Generated by RmaService
    # under a company-row lock (no race on the progressive).
    number = models.CharField(max_length=32)
    status = models.CharField(max_length=30, choices=constants.RMA_STATUSES, default=constants.RMA_STATUS_OPEN)
    reason_code = models.CharField(max_length=30, choices=constants.RMA_REASON_CODES, default=constants.RMA_REASON_OTHER)
    notes = models.TextField(blank=True)

    created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='return_orders')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('company', 'number')
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['company', 'status']),
        ]

    def clean(self):
        super().clean()
        if self.kind == constants.RMA_KIND_CUSTOMER_RETURN:
            if not self.customer_id:
                raise ValidationError({'customer': "A customer return requires a customer."})
            if self.supplier_id:
                raise ValidationError({'supplier': "A customer return cannot have a supplier."})
        elif self.kind == constants.RMA_KIND_SUPPLIER_RETURN:
            if not self.supplier_id:
                raise ValidationError({'supplier': "A supplier return requires a supplier."})
            if self.customer_id:
                raise ValidationError({'customer': "A supplier return cannot have a customer."})
        if self.customer_id and self.customer.company_id != self.company_id:
            raise ValidationError({'customer': "customer belongs to a different company."})
        if self.supplier_id and self.supplier.company_id != self.company_id:
            raise ValidationError({'supplier': "supplier belongs to a different company."})
        if self.sales_order_id and self.sales_order.company_id != self.company_id:
            raise ValidationError({'sales_order': "sales_order belongs to a different company."})
        if self.purchase_order_id and self.purchase_order.company_id != self.company_id:
            raise ValidationError({'purchase_order': "purchase_order belongs to a different company."})

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.number} [{self.kind}] ({self.status})"


class ReturnOrderLine(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    return_order = models.ForeignKey(ReturnOrder, on_delete=models.CASCADE, related_name='lines')
    product_model = models.ForeignKey(ProductModel, on_delete=models.PROTECT, related_name='return_order_lines')
    # For SERIALIZED returns the specific item; for BATCH the originating batch.
    physical_product = models.ForeignKey(
        PhysicalProduct, null=True, blank=True, on_delete=models.SET_NULL, related_name='return_order_lines',
    )
    batch = models.ForeignKey(
        ProductBatch, null=True, blank=True, on_delete=models.SET_NULL, related_name='return_order_lines',
    )
    quantity = models.DecimalField(max_digits=12, decimal_places=4)
    resolution = models.CharField(
        max_length=30, choices=constants.RMA_RESOLUTIONS, default=constants.RMA_RESOLUTION_PENDING,
    )
    resolved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['id']

    def clean(self):
        super().clean()
        if self.quantity is None or self.quantity <= 0:
            raise ValidationError({'quantity': "Quantity must be positive."})
        if self.product_model_id and self.return_order_id \
                and self.product_model.company_id != self.return_order.company_id:
            raise ValidationError({'product_model': "product_model belongs to a different company."})

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.return_order.number}: {self.quantity}× {self.product_model.sku} [{self.resolution}]"
