"""Sales orders: ordered → confirmed → picking → shipped flow.

A SalesOrder records what a Customer ordered at which unit price. Confirming an
order reserves stock for each line (ReservationService, RESERVATIONS-01);
shipping against its lines generates the outbound Movements (LedgerService,
consuming the reservation). ``quantity_shipped`` on each line is denormalized
and only updated by SalesService under row lock — mirror of PurchaseOrderLine.
"""
import uuid
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.db import models

from core.models import Company, User
from .core import ProductModel
from .customers import Customer

SO_STATUS_DRAFT = 'DRAFT'
SO_STATUS_CONFIRMED = 'CONFIRMED'
SO_STATUS_PICKING = 'PICKING'
SO_STATUS_PARTIALLY_SHIPPED = 'PARTIALLY_SHIPPED'
SO_STATUS_SHIPPED = 'SHIPPED'
SO_STATUS_CANCELLED = 'CANCELLED'

SO_STATUS_CHOICES = [
    (SO_STATUS_DRAFT, 'Draft'),
    (SO_STATUS_CONFIRMED, 'Confirmed'),
    (SO_STATUS_PICKING, 'Picking'),
    (SO_STATUS_PARTIALLY_SHIPPED, 'Partially shipped'),
    (SO_STATUS_SHIPPED, 'Shipped'),
    (SO_STATUS_CANCELLED, 'Cancelled'),
]


class SalesOrder(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='sales_orders')
    # PROTECT: an order is a commercial document — the customer on it must
    # survive as long as the order does.
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, related_name='sales_orders')
    # Sequential per company: SO-{year}-{progressive}. Generated by
    # SalesService under a company-row lock (no race on the progressive).
    number = models.CharField(max_length=32)
    status = models.CharField(max_length=30, choices=SO_STATUS_CHOICES, default=SO_STATUS_DRAFT)
    promised_at = models.DateField(null=True, blank=True)
    notes = models.TextField(blank=True)

    created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='sales_orders')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('company', 'number')
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['company', 'status']),
        ]

    def clean(self):
        super().clean()
        if self.customer_id and self.customer.company_id != self.company_id:
            raise ValidationError({'customer': "customer belongs to a different company."})

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.number} ({self.customer}) [{self.status}]"


class SalesOrderLine(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sales_order = models.ForeignKey(SalesOrder, on_delete=models.CASCADE, related_name='lines')
    product_model = models.ForeignKey(ProductModel, on_delete=models.PROTECT, related_name='sales_order_lines')

    quantity_ordered = models.DecimalField(max_digits=12, decimal_places=4)
    unit_price = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    # Denormalized; only SalesService.ship updates it, under
    # select_for_update on this row.
    quantity_shipped = models.DecimalField(max_digits=12, decimal_places=4, default=Decimal('0'))

    class Meta:
        unique_together = ('sales_order', 'product_model')
        ordering = ['id']

    @property
    def quantity_pending(self) -> Decimal:
        return self.quantity_ordered - self.quantity_shipped

    def clean(self):
        super().clean()
        if self.quantity_ordered is None or self.quantity_ordered <= 0:
            raise ValidationError({'quantity_ordered': "Ordered quantity must be positive."})
        if self.unit_price is not None and self.unit_price < 0:
            raise ValidationError({'unit_price': "Unit price cannot be negative."})
        if self.product_model_id and self.sales_order_id \
                and self.product_model.company_id != self.sales_order.company_id:
            raise ValidationError({'product_model': "product_model belongs to a different company."})

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.sales_order.number}: {self.quantity_ordered}× {self.product_model.sku}"
