"""Inter-site transfers with an in-transit state (TRANSFERS-07).

A ``TransferOrder`` moves goods between two real locations of the *same*
company with latency: a ship step parks the goods in the company's single
virtual ``In Transit`` location, and a (possibly partial) receive step lands
them at the destination. Whatever never arrives is reported as a shortage and
booked to LOSS — the transit buffer must never accumulate phantom residuals.

The ledger is untouched: every stock change goes through
``LedgerService.transfer_stock`` (see services/transfers.py). ``quantity_sent``
and ``quantity_received`` on each line are denormalized and only mutated by
``TransferService`` under ``select_for_update``.

For zero-latency moves inside a single site, keep using the direct
``LedgerService.transfer_stock`` / widget ``transfer/`` endpoint — the
``TransferOrder`` is for tracts with a real gap between dispatch and arrival.
"""

import uuid
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.db import models

from core.models import Company, User
from .core import Location, ProductModel
from .tracking import PhysicalProduct, ProductBatch

TR_STATUS_DRAFT = "DRAFT"
TR_STATUS_IN_TRANSIT = "IN_TRANSIT"
TR_STATUS_PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
TR_STATUS_RECEIVED = "RECEIVED"
TR_STATUS_CANCELLED = "CANCELLED"

TR_STATUS_CHOICES = [
    (TR_STATUS_DRAFT, "Draft"),
    (TR_STATUS_IN_TRANSIT, "In transit"),
    (TR_STATUS_PARTIALLY_RECEIVED, "Partially received"),
    (TR_STATUS_RECEIVED, "Received"),
    (TR_STATUS_CANCELLED, "Cancelled"),
]


class TransferOrder(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="transfer_orders")
    # PROTECT: a transfer is a logistics document — the endpoints it names must
    # outlive the document itself.
    from_location = models.ForeignKey(
        Location, on_delete=models.PROTECT, related_name="transfer_orders_out"
    )
    to_location = models.ForeignKey(
        Location, on_delete=models.PROTECT, related_name="transfer_orders_in"
    )
    # Sequential per company: TR-{year}-{progressive}. Generated by
    # TransferService.next_number under a company-row lock (no race).
    number = models.CharField(max_length=32)
    status = models.CharField(max_length=30, choices=TR_STATUS_CHOICES, default=TR_STATUS_DRAFT)
    notes = models.TextField(blank=True)

    shipped_at = models.DateTimeField(null=True, blank=True)
    received_at = models.DateTimeField(null=True, blank=True)

    created_by = models.ForeignKey(
        User, null=True, on_delete=models.SET_NULL, related_name="transfer_orders"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("company", "number")
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["company", "status"]),
        ]

    def clean(self):
        super().clean()
        if self.from_location_id and self.from_location.company_id != self.company_id:
            raise ValidationError(
                {"from_location": "from_location belongs to a different company."}
            )
        if self.to_location_id and self.to_location.company_id != self.company_id:
            raise ValidationError({"to_location": "to_location belongs to a different company."})
        if (
            self.from_location_id
            and self.to_location_id
            and self.from_location_id == self.to_location_id
        ):
            raise ValidationError({"to_location": "Source and destination must differ."})

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.number} ({self.from_location} → {self.to_location}) [{self.status}]"


class TransferOrderLine(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    transfer_order = models.ForeignKey(
        TransferOrder, on_delete=models.CASCADE, related_name="lines"
    )
    product_model = models.ForeignKey(
        ProductModel, on_delete=models.PROTECT, related_name="transfer_order_lines"
    )
    # Optional pin to a specific batch (BATCH/PERISHABLE) or unit (SERIALIZED).
    batch = models.ForeignKey(
        ProductBatch,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="transfer_lines",
    )
    physical_product = models.ForeignKey(
        PhysicalProduct,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="transfer_lines",
    )

    quantity_sent = models.DecimalField(max_digits=12, decimal_places=4)
    # Denormalized; only TransferService.receive updates it under row lock.
    quantity_received = models.DecimalField(max_digits=12, decimal_places=4, default=Decimal("0"))
    # Denormalized loss (shortage) so sent == received + shortage + in_transit.
    quantity_shortage = models.DecimalField(max_digits=12, decimal_places=4, default=Decimal("0"))

    class Meta:
        ordering = ["id"]

    @property
    def quantity_in_transit(self) -> Decimal:
        """Still parked in the virtual In Transit location for this line."""
        return self.quantity_sent - self.quantity_received - self.quantity_shortage

    def clean(self):
        super().clean()
        if self.quantity_sent is None or self.quantity_sent <= 0:
            raise ValidationError({"quantity_sent": "Sent quantity must be positive."})
        if (
            self.product_model_id
            and self.transfer_order_id
            and self.product_model.company_id != self.transfer_order.company_id
        ):
            raise ValidationError(
                {"product_model": "product_model belongs to a different company."}
            )

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.transfer_order.number}: {self.quantity_sent}× {self.product_model.sku}"
