# Generated by Django 4.2.27 on 2026-01-20 22:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apikey_default_location'),
        ('inventory', '0003_product_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('engine_type', models.CharField(choices=[('counter', 'Counter (Discrete)'), ('converter', 'Converter (Continuous)'), ('bucket', 'Bucket (Segmented)')], max_length=50)),
                ('engine_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_templates', to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='default_calculator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_models', to='inventory.calculatortemplate'),
        ),
    ]
