# Generated by Django 4.2.27 on 2026-01-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_productbatch_inventorystrategy_movement_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystrategy',
            name='type',
            field=models.CharField(choices=[('BUCKET', 'Bucket / Batch Tracking'), ('ASSEMBLY', 'Assembly / Kit'), ('CONVERTER', 'Converter / Continuous'), ('TIME', 'Time-Based (Rental/Booking)'), ('DIMENSION', 'Dimension (Area/Linear)'), ('IOT', 'IoT Threshold / Trigger'), ('MULTI_CURVE', 'Multi-Curve Converter')], max_length=50),
        ),
    ]
