# Generated by Django 4.2.27 on 2026-01-22 22:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_productmodel_min_stock_threshold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="min_stock_threshold",
        ),
    ]
