# Generated by Django 4.2.27 on 2026-01-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_productmodel_min_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='engine_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='engine_type',
            field=models.CharField(choices=[('counter', 'Counter (Discrete)'), ('converter', 'Converter (Continuous)'), ('bucket', 'Bucket (Segmented)')], default='counter', max_length=50),
        ),
    ]
