# Generated by Django 4.2.27 on 2026-01-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_productmodel_engine_config_productmodel_engine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatortemplate',
            name='engine_type',
            field=models.CharField(choices=[('counter', 'Counter (Discrete)'), ('converter', 'Converter (Continuous)'), ('bucket', 'Bucket (Segmented)'), ('tracker', 'Item Tracker (Serialized)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='engine_type',
            field=models.CharField(choices=[('counter', 'Counter (Discrete)'), ('converter', 'Converter (Continuous)'), ('bucket', 'Bucket (Segmented)'), ('tracker', 'Item Tracker (Serialized)')], default='counter', max_length=50),
        ),
    ]
