# Generated by Django 4.2.27 on 2026-01-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_location_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('STORE', 'Store'), ('CONTAINER', 'Container'), ('LOSS', 'Loss'), ('VIRTUAL', 'Virtual')], max_length=50),
        ),
    ]
