# Generated by Django 4.2.27 on 2026-01-26 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_physicalproduct_work_order_productbatch_work_order_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productbatch",
            unique_together={("product_model", "location", "batch_identifier", "work_order")},
        ),
    ]
