# Generated by Django 4.2.27 on 2026-01-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_alter_productbatch_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="product_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="inventory.productmodel",
            ),
        ),
    ]
