# Generated by Django 4.2.27 on 2026-01-27 21:32

from django.db import migrations, models
import django.db.models.deletion
import inventory.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_apikey_default_location"),
        ("inventory", "0020_alter_movement_product_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicQRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=inventory.models.generate_qr_code, max_length=12, unique=True
                    ),
                ),
                (
                    "custom_url",
                    models.URLField(
                        blank=True, help_text="External URL (overrides product links)", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VIRGIN", "Not Configured"),
                            ("CONFIGURED", "Configured"),
                            ("LOCKED", "Locked"),
                        ],
                        default="VIRGIN",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Optional friendly name", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="core.company",
                    ),
                ),
                (
                    "physical_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_codes",
                        to="inventory.physicalproduct",
                    ),
                ),
                (
                    "product_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_codes",
                        to="inventory.productmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic QR Code",
                "verbose_name_plural": "Dynamic QR Codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
