# Generated by Django 4.2.27 on 2026-02-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0024_workorder_product_model_productcomponent"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["occurred_at"], name="inventory_m_occurre_eb465d_idx"),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["work_order"], name="inventory_m_work_or_33aa48_idx"),
        ),
    ]
