# Generated by Django 4.2.27 on 2026-02-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0025_movement_inventory_m_occurre_eb465d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="product",
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="inventory.productmodel",
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
