# Generated by Django 4.2.28 on 2026-02-11 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_apikey_is_active"),
        ("inventory", "0028_alter_location_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("company", "name")},
        ),
    ]
