# Generated by Django 4.2.28 on 2026-02-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_dynamicqrcode_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicqrcode',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Specific Work Order / Kit context', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='inventory.workorder'),
        ),
    ]
