# Generated by Django 4.2.28 on 2026-05-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0039_add_updated_at_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="profile",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIMPLE_COUNT", "Simple Count"),
                    ("UNIT_CONVERSION", "Unit Conversion"),
                    ("DIMENSIONAL", "Dimensional (Area/Volume)"),
                    ("BATCH_TRACKED", "Batch / Lot Tracked"),
                    ("PERISHABLE", "Perishable / Time-Based"),
                    ("SERIALIZED", "Serialized / Individual"),
                    ("ASSEMBLED", "Assembled / Kit"),
                ],
                help_text="Inventory profile — single-axis replacement for tracking_mode + engine_type + strategy_type",
                max_length=50,
                null=True,
            ),
        ),
    ]
