# Generated by Django 4.2.28 on 2026-05-19 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0046_populate_monitoring_product_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="strategy",
        ),
    ]
