# Generated by Django 4.2.28 on 2026-05-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_remove_productmodel_strategy_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringrule',
            name='strategy',
        ),
        migrations.DeleteModel(
            name='InventoryStrategy',
        ),
    ]
