# Generated by Django 4.2.28 on 2026-05-19 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0048_remove_inventorystrategy_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="_engine_type",
        ),
        migrations.RemoveField(
            model_name="productmodel",
            name="_tracking_mode",
        ),
    ]
