# Generated by Django 4.2.28 on 2026-05-24 20:01

from decimal import Decimal, InvalidOperation
from django.db import migrations, models


def copy_min_threshold_to_field(apps, schema_editor):
    """Copy attributes['min_threshold'] → reorder_threshold for back-compat.

    Leaves the attribute key in place for one release so any external readers
    keep working; a later migration can drop it once Kanban is the sole source.
    """
    ProductModel = apps.get_model('inventory', 'ProductModel')
    updated = 0
    for pm in ProductModel.objects.exclude(attributes={}):
        raw = (pm.attributes or {}).get('min_threshold')
        if raw is None:
            continue
        try:
            pm.reorder_threshold = Decimal(str(raw))
        except (InvalidOperation, ValueError, TypeError):
            continue
        pm.save(update_fields=['reorder_threshold'])
        updated += 1
    if updated:
        print(f"  Copied min_threshold → reorder_threshold for {updated} products.")


def reverse_copy(apps, schema_editor):
    """Reverse: null out reorder_threshold (attributes still intact)."""
    ProductModel = apps.get_model('inventory', 'ProductModel')
    ProductModel.objects.update(reorder_threshold=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_supplier_movement_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='critical_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Drop below = CRITICAL column. Defaults to reorder_threshold/2 when null at scoring time.', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='max_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Above = OVERSTOCK swimlane', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='reorder_qty',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Suggested qty to reorder; default = max_threshold - current at scoring time', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='reorder_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Min on-hand qty before product enters REORDER column', max_digits=19, null=True),
        ),
        migrations.RunPython(copy_min_threshold_to_field, reverse_copy),
    ]
