# Generated by Django 4.2.30 on 2026-06-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auditlog'),
        ('inventory', '0055_backfill_movement_product_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicqrcode',
            name='api_key',
            field=models.ForeignKey(blank=True, help_text='API Key used for widget access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='core.apikey'),
        ),
    ]
