# Generated by Django 4.2.30 on 2026-06-14 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0063_transfer_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CUSTOMER_RETURN', 'Customer return'), ('SUPPLIER_RETURN', 'Supplier return')], max_length=30)),
                ('number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RECEIVED', 'Received'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30)),
                ('reason_code', models.CharField(choices=[('DEFECTIVE', 'Defective'), ('WRONG_ITEM', 'Wrong item'), ('EXPIRED', 'Expired'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_orders', to='inventory.customer')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='inventory.purchaseorder')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='inventory.salesorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_orders', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='is_sellable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ReturnOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('resolution', models.CharField(choices=[('PENDING', 'Pending'), ('RESTOCK', 'Restock'), ('SCRAP', 'Scrap'), ('RETURN_TO_SUPPLIER', 'Return to supplier')], default='PENDING', max_length=30)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_order_lines', to='inventory.productbatch')),
                ('physical_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_order_lines', to='inventory.physicalproduct')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_order_lines', to='inventory.productmodel')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.returnorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='returnorder',
            index=models.Index(fields=['company', 'status'], name='inventory_r_company_33d0d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='returnorder',
            unique_together={('company', 'number')},
        ),
    ]
