# Generated by Django 4.2.30 on 2026-06-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_rma_and_quarantine'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='barcode',
            field=models.CharField(blank=True, default='', help_text='GTIN / EAN-8 / EAN-13 / UPC-A barcode printed by the manufacturer. Unique per company when set.', max_length=14),
        ),
        migrations.AddConstraint(
            model_name='productmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('company', 'barcode'), name='uniq_company_barcode_when_set'),
        ),
    ]
