# Generated by Django 4.2.27 on 2026-01-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
