# Generated by Django 4.2.27 on 2026-01-08 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_physicalproduct_unique_together_and_more"),
        ("core", "0004_apikey_allowed_domains_alter_license_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="default_location",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, the widget will skip location selection and force this location.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.location",
            ),
        ),
    ]
