# Generated by Django 4.2.30 on 2026-05-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_company_account_type_company_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="vat",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Partita IVA — unique business identifier. Null allowed for legacy rows; required at new registration.",
                max_length=13,
                null=True,
                unique=True,
            ),
        ),
    ]
