# Generated by Django 4.2.30 on 2026-05-21 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_company_created_at_company_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("COMPANY_PROVISIONED", "Company provisioned"),
                            ("TIER_CHANGED", "Tier changed"),
                            ("COMPANY_SUSPENDED", "Company suspended"),
                            ("COMPANY_REACTIVATED", "Company reactivated"),
                            ("USER_INVITED", "User invited"),
                            ("LOGIN", "Login"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Action context, e.g. {from, to} tier."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action. Null if the actor was deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company the action targeted, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
